version: "3.9"
services:
  controlplane:
    build:
      context: ../../..
      dockerfile: ops/deploy/docker/dockerfiles/controlplane.Dockerfile
    ports: ["8080:8080"]
  mgmtapi:
    build:
      context: ../../..
      dockerfile: ops/deploy/docker/dockerfiles/mgmtapi.Dockerfile
    ports: ["8081:8081"]
