{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "qbitel-bridge.namespace" . }}
  labels:
    {{- include "qbitel-bridge.labels" . | nindent 4 }}
    qbitel.ai/managed: "true"
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
