{{- if .Values.security.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qbitel-bridge.serviceAccountName" . }}
  namespace: {{ include "qbitel-bridge.namespace" . }}
  labels:
    {{- include "qbitel-bridge.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
---
{{- if .Values.xdsServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qbitel-xds-server
  namespace: {{ include "qbitel-bridge.namespace" . }}
  labels:
    {{- include "qbitel-bridge.xdsServer.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.admissionWebhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qbitel-admission-webhook
  namespace: {{ include "qbitel-bridge.namespace" . }}
  labels:
    {{- include "qbitel-bridge.admissionWebhook.labels" . | nindent 4 }}
{{- end }}
{{- end }}
