{{- if .Values.security.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cronos-ai.serviceAccountName" . }}
  namespace: {{ include "cronos-ai.namespace" . }}
  labels:
    {{- include "cronos-ai.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
---
{{- if .Values.xdsServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronos-xds-server
  namespace: {{ include "cronos-ai.namespace" . }}
  labels:
    {{- include "cronos-ai.xdsServer.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.admissionWebhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronos-admission-webhook
  namespace: {{ include "cronos-ai.namespace" . }}
  labels:
    {{- include "cronos-ai.admissionWebhook.labels" . | nindent 4 }}
{{- end }}
{{- end }}
